### ISSUE TITLE
Occasional crash: video mixer

### ISSUE THREAD

**Issue by jgh-** [unpause-live/SwiftVideo#19]
Relevant stack trace
```
#0  0x00007fd0532179a8 in _swift_release_dealloc () at /usr/lib/swift/linux/libswiftCore.so
#1  0x00007fd05320f4fb in swift_arrayDestroy () at /usr/lib/swift/linux/libswiftCore.so
#2  0x00007fd052fecb07 in $ss18_DictionaryStorageCfd () at /usr/lib/swift/linux/libswiftCore.so
#3  0x00007fd052fecc99 in $ss18_DictionaryStorageCfD () at /usr/lib/swift/linux/libswiftCore.so
#4  0x00007fd0532179ab in _swift_release_dealloc () at /usr/lib/swift/linux/libswiftCore.so
#5  0x0000562b926feb1c in $s10SwiftVideo0B5MixerC3mix33_0B6887970F57CAB2437618B11AE13F40LL2atyAA14ClockTickEventC_tFyycfU0_6$deferL_yyF (strongSelf=...) at /root/repo/Sources/SwiftVideo/Sources/SwiftVideo/mix.video.swift:105
#6  0x0000562b926fe5a7 in $s10SwiftVideo0B5MixerC3mix33_0B6887970F57CAB2437618B11AE13F40LL2atyAA14ClockTickEventC_tFyycfU0_ ()
    at /root/repo/Sources/SwiftVideo/Sources/SwiftVideo/mix.video.swift:104
#7  0x0000562b921ba329 in $sIeg_IeyB_TR ()
#8  0x00007fd053524547 in _dispatch_call_block_and_release () at /usr/lib/swift/linux/libdispatch.so
#9  0x00007fd05353000b in _dispatch_lane_serial_drain () at /usr/lib/swift/linux/libdispatch.so
#10 0x00007fd053530cea in _dispatch_lane_invoke () at /usr/lib/swift/linux/libdispatch.so
#11 0x00007fd053538baa in _dispatch_worker_thread () at /usr/lib/swift/linux/libdispatch.so
#12 0x00007fd052c396db in start_thread (arg=0x7fceecff9700) at pthread_create.c:463
#13 0x00007fd03f9ef88f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

relevant loc:
https://github.com/unpause-live/SwiftVideo/blob/master/Sources/SwiftVideo/mix.video.swift#L105

**Comment by jgh-** [comment]
Fixed by 58fec27f1a0bb9e2bc323b6fefac9902990af151
